#!/bin/bash

# ${1} Storage path
# ${2} Location name
# ${3} Tracker code binary

# create output directory #
mkdir -p ${1}/regbl_analysis/analysis_${2}/${2}_potential/potential_timeline

# reading reference file line by line #
while IFS= read -r regbl_egid; do

    # display message #
    echo "Processing ${regbl_egid} ..."

    # create timeline for the egid #
    ${3} -s ${1} -l ${2} -g ${regbl_egid} -e ${1}/regbl_analysis/analysis_${2}/${2}_potential/potential_timeline

# egid file #
done < "${1}/regbl_analysis/analysis_${2}/${2}_potential/potential"
