#!/bin/bash
#  regbl-poc-analysis
#
#      Nils Hamel - nils.hamel@alumni.epfl.ch
#      Huriel Reichel
#      Copyright (c) 2020-2021 Republic and Canton of Geneva
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

# regbl-poc-analysis-potential
#
# This script is used to compute the timeline of the selected buildings in the
# potentially valid reference list.
#
# ${1} Storage path
# ${2} Tracker code binary

# create output directory #
mkdir -p ${1}/regbl_analysis/analysis_potential/potential_timeline

# reading reference file line by line #
while IFS= read -r regbl_egid; do

    # display message #
    echo "Processing ${regbl_egid} ..."

    # create timeline for the egid #
    ${2} -s ${1} -g ${regbl_egid} -e ${1}/regbl_analysis/analysis_potential/potential_timeline

# egid file #
done < "${1}/regbl_analysis/analysis_potential/potential"
