#!/bin/bash
#  regbl-poc-analysis
#
#      Nils Hamel - nils.hamel@alumni.epfl.ch
#      Huriel Reichel
#      Copyright (c) 2020-2021 Republic and Canton of Geneva
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

# regbl-poc-analyse-timeline
#
# This script is used to create a timeline, composed of crops of maps centered
# on selected building, showing the evolution of the building and the results
# of the detection using color shemes
#
# The script makes a random selection of a given amount of buildings using the
# list of available building.
#
# As the software used to create the timeline is not expected to be available in
# the system path, the binary of the software has to be provided as parameter.

# ${1} : Storage path
# ${2} : Number of building to randomly select
# ${3} : Path of tracker binary

# create exportation directory #
mkdir -p ${1}/regbl_analysis/analysis_timeline-random

# random selection loop #
for regbl_i in $(seq 1 ${2}); do

    # random selection of building #
    regbl_id=$(ls ${1}/regbl_output/output_egid | shuf -n 1)

    # display message #
    echo "Compute timeline for EGID ${regbl_id} ..."

    # create the time line #
    ${3} -s ${1} -g ${regbl_id} -e ${1}/regbl_analysis/analysis_timeline-random

done
